/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "slkzhdowugzwkahyldzk"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsa3poZG93dWd6d2thaHlsZHprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQyNzQ4NzcsImV4cCI6MjA3OTg1MDg3N30.GL-WruVzLtptANjhYTb3-_4f98RU89NR-wr6G97R4KU"